const ROUTES = {
  WELCOME: "Welcome",
  WELCOME_NAVIGATOR: "WelcomeNavigator",
  HOME: "Home",
  HOME_NAVIGATOR: "HomeNavigator",
  FOLLOWING: "Following",
  SUGGESTION_ACCOUNT: "SuggestionAccount",
  FOLLOWING: "Following",
  FOLLOWER: "Follower",

  SEARCH: "Search",
  HASHTAG_RESULT: '"HashtagResult"',
  SEARCH_NAVIGATOR: "SearchNavigator",
  POST: "Post",
  POST_DETAIL: "PostDetail",
  HASHTAG_DETAIL: "HashtagDetail",

  POST_NAVIGATOR: "PostNavigator",
  NOTIFICATION: "Notification",
  NOTIFICATION_NAVIGATOR: "NotificationNavigator",
  PROFILE: "Profile",
  PROFILE_NAVIGATOR: "ProfileNavigator",
  SETTING: "Setting",
  SETTING_NAVIGATOR: "SettingNavigator",
  UPDATEPROFILE: "UpdateProfile",
  UPDATEPROFILE_NAVIGATOR: "UpdateProfileNavigator",
  CARTDETAIL: "CartDetail",
  CARTDETAIL_NAVIGATOR: "CartDetailNavigator",
  FRIENDS: "Friends",
  FRIENDS_NAVIGATOR: "FriendsNavigator",
  SETTINGFRIENDS: "SettingFriends",
  SETTINGFRIENDS_NAVIGATOR: "SettingFriendsNavigator",
  LISTFOLLOW: "ListFollow",
  LISTFOLLOW_NAVIGATOR: "ListFollowNavigator",

  LISTLIKE: "ListLike",
  LISTLIKE_NAVIGATOR: "ListLikeNavigator",
  UPDATEPASSWORD: "UpdatePasswordScreen",
  HASHTAGVIEW: "HashtagView",
  HASHTAGVIEW_NAVIGATOR: "HashtagViewNavigator",
  SETTINGPACKAGE: "SettingPackage",
  SETTINGPACKAGE_NAVIGATOR: "SettingPackageNavigator",
  MOREINFO: "MoreInfo",
  MOREINFO_NAVIGATOR: "MoreInfoNavigator",
  PACKAGEHISTORY: "PackageHistory",

  CHAT: "Chat",
  CHAT_NAVIGATOR: "ChatNavigator",
  REPORTUSER: "ReportUser",
  REPORTUSER_NAVIGATOR: "ReportUserNavigator",
  REPORTPOST: "ReportPost",
  REPORTPOST_NAVIGATOR: "ReportPostNavigator",
  UPPOST: "UpPost",
  UPPOSTDRAFT: "UpPostDraft",
  UPPOST_NAVIGATOR: "UpPostNavigator",
  EDIT_POST: "EditPost",
  LIBRARY_IAMGE: "LibraryImage",

  CONVERSATIONS: "ConversationsScreens",
  MESSAGESSCREEN: "MessagesScreen",

  FORGOTPASSWORD: 'ForgotPassword',
};
export default ROUTES;
